'use client';
import { useState,useTransition } from 'react';
import { runOperation } from './ops-actions';
import type { Committee } from '@/lib/types';
type Person={id:string;name:string;registration_ref:string};
export function AllocationBoard({people,committees,initial,reservations}:{people:Person[];committees:Committee[];initial:{participant_id:string;committee_slug:string;country:string}[];reservations:{committee_slug:string;country:string}[]}){
  const [selected,setSelected]=useState('');const [allocations,setAllocations]=useState(initial);const [message,setMessage]=useState('');const [pending,start]=useTransition();
  function allocate(participant_id:string,committee_slug:string,country:string){if(!participant_id)return;start(async()=>{const r=await runOperation('allocation',{participant_id,committee_slug,country});setMessage(r.error||'Allocation saved.');if(!r.error)setAllocations(old=>[...old.filter(a=>a.participant_id!==participant_id),{participant_id,committee_slug,country}]);});}
  return <div className="admin-card"><h2>Allocation board</h2><p>Drag a delegate onto a country, or select a delegate and press Assign. The database checks capacity and country conflicts.</p><label>Selected delegate<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Choose delegate</option>{people.map(p=><option key={p.id} value={p.id}>{p.name} · {p.registration_ref}</option>)}</select></label><div className="flex flex-wrap gap-2 my-4">{people.filter(p=>!allocations.some(a=>a.participant_id===p.id)).map(p=><button key={p.id} draggable onDragStart={e=>e.dataTransfer.setData('text/plain',p.id)} onClick={()=>setSelected(p.id)}>{p.name}</button>)}</div><p role="status">{message}</p><div className="grid md:grid-cols-2 gap-4">{committees.map(c=><section key={c.id} className="border rounded p-4"><h3>{c.name} — {allocations.filter(a=>a.committee_slug===c.slug).length}/{c.capacity??'unlimited'}</h3>{c.countryList.map(country=>{const allocation=allocations.find(a=>a.committee_slug===c.slug&&a.country===country.country);const reserved=reservations.some(r=>r.committee_slug===c.slug&&r.country===country.country);return <div key={country.country} className="flex justify-between items-center gap-3 border-b py-3" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!allocation&&!reserved)allocate(e.dataTransfer.getData('text/plain'),c.slug,country.country);}}><span>{country.country} {allocation?`— ${people.find(p=>p.id===allocation.participant_id)?.name||'Assigned'}`:reserved?'— Reserved':''}</span><button disabled={pending||!selected||Boolean(allocation)||reserved} onClick={()=>allocate(selected,c.slug,country.country)}>Assign</button></div>;})}</section>)}</div></div>;
}
