 'use client';
import { useState,useTransition } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { SchemaForm,emptyValue,type Schema } from './SchemaForm';
import { saveContent,saveSettings,restoreRevision,cancelSchedule } from './content-actions';
import type { ContentEntry } from '@/lib/content/registry';
import { MediaUpload } from './MediaUpload';
import { useDirtyGuard } from './useDirtyGuard';
const groups:Record<string,string[]>={ 'Event details':['eventNames','hostInstitution','venue','eventDates','galaDate','phaseOverride'], 'Registration & fees':['registrationDeadlines','registrationStatus','fees','feeAmounts','paymentInstructions','memorialDeadline'], 'Contact & arrival':['contactEmails','contactPhone','checkinDesk','entryRequirement','replyTime'], 'Scoring & results':['mootScoring','gimunRubric','resultsPublished'], 'Website copy':['socialLinks','footerBlurb','privacyNotice','stats'] };
function localTime(value:string|null){return value?new Date(new Date(value).getTime()+5*3600000).toISOString().slice(0,16):'';}
function utc(value:string){return value?new Date(`${value}:00+05:00`).toISOString():null;}
type Saved={fieldErrors?:Record<string,string>;error?:string;version?:number;entry?:ContentEntry;data?:Record<string,unknown>};
export function ContentEditor({initial,schema,settings=false,readOnly=false,revisions=[],media=[],resources=[],upload=false,liveVersion=null,scheduledAt=null,resultsReleased=true}:{initial:ContentEntry;schema:Schema;settings?:boolean;readOnly?:boolean;revisions?:{id:number;created_at:string}[];media?:{url:string;alt:string;mime:string;size:number}[];resources?:{id:string;title:string}[];upload?:boolean;liveVersion?:number|null;scheduledAt?:string|null;resultsReleased?:boolean}){
 const initialize=()=>({...initial,id:settings?'site':String(initial.data.id||initial.id),data:{...(emptyValue(schema) as Record<string,unknown>),...initial.data}});
 const [entry,setEntry]=useState(initialize),[dirty,setDirty]=useState(false),[seen,setSeen]=useState(initial.version),[fieldErrors,setFieldErrors]=useState<Record<string,string>>({}),[message,setMessage]=useState(''),[mode,setMode]=useState('draft');const [pending,start]=useTransition();const router=useRouter();useDirtyGuard(dirty);
 if(seen!==initial.version){setSeen(initial.version);if(!dirty)setEntry(initialize());}
 const conflict=dirty&&entry.version!==initial.version;
 function execute(operation:()=>Promise<Saved>,success='Saved.') {start(async()=>{try{const result=await operation();setMessage(result.error||success);setFieldErrors(result.fieldErrors||{});if(result.error){requestAnimationFrame(()=>document.querySelector<HTMLElement>('[aria-invalid=true]')?.focus());return;}if(result.version)setEntry(old=>({...old,...result.entry,data:result.entry?.data||result.data||old.data,version:result.version!}));setDirty(false);if(!settings&&initial.version===0&&entry.id)router.replace(`/admin/content/${entry.collection}/${entry.id}`);router.refresh();}catch{setMessage('Could not save. Your changes are still here; check your connection and try again.');}});}
 const mediaField=initial.collection==='resources'?'fileUrl':initial.collection==='gallery'?'image':initial.collection==='sponsors'?'logo':['team','results'].includes(initial.collection)?'photo':null;
 const resourceField=initial.collection==='committees'?'backgroundGuideDocId':initial.collection==='moot-categories'?'propositionDocId':null;
 const chooseMedia=(asset:{url:string;mime:string;size:number})=>{setDirty(true);setEntry(old=>({...old,data:{...old.data,[mediaField!]:asset.url,...(initial.collection==='resources'?{fileSize:`${(asset.size/1024).toFixed(1)} KB`,fileFormat:asset.mime==='application/pdf'?'PDF':asset.mime.split('/')[1].toUpperCase(),versionDate:new Date().toISOString().slice(0,10)}:{})}}));};
 const change=(v:unknown)=>{const data=v as Record<string,unknown>;setDirty(true);setEntry({...entry,data,id:settings?'site':String(data.id||entry.id)});};
 function save(){if(settings){execute(()=>saveSettings(entry.data,entry.version),'Settings saved and applied to the website.');return;}if(mode==='schedule'&&(!entry.publish_at||new Date(entry.publish_at).getTime()<=Date.now())){setMessage('Choose a future publication time in Asia/Karachi.');return;}if(scheduledAt&&mode!=='draft'&&!window.confirm('This will replace or cancel the pending scheduled publication. Continue?'))return;if(mode==='archive'&&!window.confirm('Remove this entry from the website and cancel its pending publication?'))return;if(mode!=='draft'&&entry.collection==='announcements'&&entry.data.pinnedFlag&&!window.confirm('This publication will replace the pinned announcement when it becomes live. Continue?'))return;execute(()=>saveContent({...entry,status:mode==='draft'?'draft':mode==='archive'?'archived':'published',publish_at:mode==='schedule'?entry.publish_at:null,expire_at:mode==='draft'||mode==='archive'?null:entry.expire_at}),mode==='draft'?'Draft saved. The public version is unchanged.':mode==='schedule'?'Publication scheduled. The current version stays live.':mode==='archive'?'Entry unpublished.':'Published. Connected pages update within 10 seconds.');}
 const editableSchema={...schema,properties:Object.fromEntries(Object.entries(schema.properties||{}).filter(([key])=>!['dayLabel'].includes(key)).map(([key,value])=>[key,key==='id'?{...value,readOnly:true}:value]))};
 return <div data-admin-dirty={dirty?'true':undefined}>{dirty&&<p className="admin-dirty">Unsaved changes are protected from automatic refresh. <button type="button" className="secondary" onClick={()=>{setEntry(initialize());setDirty(false);setMessage('Changes discarded.');}}>Discard changes</button></p>}{conflict&&<p role="alert">This record changed in another session. Copy your changes before discarding and loading the latest version.</p>}{!settings&&<section className="admin-card"><h2>Publication</h2><p><span className="admin-status">{liveVersion?'Live version '+liveVersion:'Not public'}</span> · Working version {entry.version}</p>{scheduledAt&&<p>Scheduled: {new Date(scheduledAt).toLocaleString('en-GB',{timeZone:'Asia/Karachi'})} PKT <button disabled={pending||readOnly} className="secondary" onClick={()=>execute(()=>cancelSchedule(entry.collection,entry.id,entry.version),'Schedule cancelled. The live version is unchanged.')}>Cancel schedule</button></p>}{entry.collection==='results'&&!resultsReleased&&<p role="alert">Results are hidden by the site-wide release setting, even after publishing this entry.</p>}{initial.version>0&&<p className="admin-toolbar">{/* A plain link: prefetching would switch preview on by itself. */}<a href={`/admin/preview?collection=${entry.collection}&id=${encodeURIComponent(initial.id)}`} target="_blank" rel="noopener">Preview on site</a><Link href={`/admin/content/${entry.collection}/${initial.id}/preview`} target="_blank">Saved fields</Link></p>}<p className="admin-description">Drafts are private. Publish immediately or capture this version for a scheduled release. Later draft edits do not alter a scheduled release.</p></section>}
 {!readOnly&&mediaField&&<section className="admin-card"><label>Choose library media<select value="" onChange={e=>{const asset=media.find(a=>a.url===e.target.value);if(asset)chooseMedia(asset);}}><option value="">Select media</option>{media.filter(a=>initial.collection==='resources'||a.mime.startsWith('image/')).map(a=><option key={a.url} value={a.url}>{a.alt}</option>)}</select></label>{upload&&<MediaUpload onUploaded={assets=>{const a=assets.find(a=>initial.collection==='resources'||a.mime.startsWith('image/'));if(a)chooseMedia(a);}}/>}</section>}
 <form className="admin-card" onSubmit={e=>{e.preventDefault();save();}}><fieldset disabled={readOnly||pending}><legend>{settings?'Site settings':'Working content'}</legend>{!settings&&resourceField&&<label>Published resource<select value={String(entry.data[resourceField]||'')} onChange={e=>change({...entry.data,[resourceField]:e.target.value})}><option value="">Choose resource</option>{resources.map(r=><option key={r.id} value={r.id}>{r.title}</option>)}</select></label>}{settings?Object.entries(groups).map(([label,keys])=><details key={label} open={label==='Event details'}><summary>{label}</summary><p className="admin-description">Changes in this group take effect immediately when you save settings.</p><SchemaForm schema={{...schema,properties:Object.fromEntries(Object.entries(schema.properties||{}).filter(([k])=>keys.includes(k)))}} value={entry.data} onChange={change} label={label} errors={fieldErrors}/></details>):<SchemaForm errors={fieldErrors} schema={editableSchema} value={entry.data} onChange={change}/>}{!settings&&<><label>Display order<input type="number" value={entry.sort_order} onChange={e=>{setDirty(true);setEntry({...entry,sort_order:Number(e.target.value)});}}/></label><label>Save action<select value={mode} onChange={e=>setMode(e.target.value)}><option value="draft">Save draft</option><option value="publish">Publish now</option><option value="schedule">Schedule publication</option><option value="archive">Unpublish / archive</option></select></label>{mode==='schedule'&&<label>Publish at · Asia/Karachi<input type="datetime-local" required value={localTime(entry.publish_at)} onChange={e=>{setDirty(true);setEntry({...entry,publish_at:utc(e.target.value)});}}/></label>}{['publish','schedule'].includes(mode)&&<label>Optional expiry · Asia/Karachi<input type="datetime-local" value={localTime(entry.expire_at)} onChange={e=>{setDirty(true);setEntry({...entry,expire_at:utc(e.target.value)});}}/></label>}</>}<button disabled={pending||readOnly||conflict}>{pending?'Saving…':settings?'Save settings':mode==='publish'?'Publish now':mode==='schedule'?'Schedule publication':mode==='archive'?'Unpublish entry':'Save draft'}</button></fieldset>{message&&<p role="status" aria-label="Save status">{message}</p>}</form><details className="admin-card"><summary>Revision history</summary><p>Restoring content creates a draft. Settings restorations apply immediately.</p>{revisions.length?revisions.map(r=><p key={r.id}>{new Date(r.created_at).toLocaleString('en-GB',{timeZone:'Asia/Karachi'})} PKT <button className="secondary" disabled={pending||readOnly} onClick={()=>execute(()=>restoreRevision(r.id,entry.version),settings?'Settings restored.':'Revision restored as a draft.')}>Restore revision {r.id}</button></p>):<p>No earlier revisions.</p>}</details></div>;
}
