'use client';
import { useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { SchemaForm, emptyValue, type Schema } from './SchemaForm';
import { saveContent, saveSettings, restoreRevision } from './content-actions';
import type { ContentEntry } from '@/lib/content/registry';
import { MediaUpload } from './MediaUpload';
export function ContentEditor({ initial, schema, settings = false, readOnly = false, revisions = [],media=[],resources=[],upload=false }: { initial: ContentEntry; schema: Schema; settings?: boolean; readOnly?: boolean; revisions?: { id: number; created_at: string }[];media?:{url:string;alt:string;mime:string;size:number}[];resources?:{id:string;title:string}[];upload?:boolean }) {
  const [entry,setEntry] = useState({ ...initial, data: { ...(emptyValue(schema) as Record<string,unknown>), ...initial.data } }); const [message,setMessage] = useState(''); const [pending,start] = useTransition(); const router = useRouter();
  const execute = (operation: () => Promise<{ error?: string; version?: number; entry?: ContentEntry; data?: Record<string,unknown> }>) => start(async () => { const result = await operation(); setMessage(result.error || 'Saved.'); if (result.version) setEntry(old => ({ ...old,...result.entry,data:result.entry?.data || result.data || old.data,version: result.version! })); router.refresh(); });
  const mediaField=initial.collection==='resources'?'fileUrl':initial.collection==='gallery'?'image':initial.collection==='sponsors'?'logo':['team','results'].includes(initial.collection)?'photo':null;
  const chooseMedia=(asset:{url:string;mime:string;size:number})=>setEntry(old=>({...old,data:{...old.data,[mediaField!]:asset.url,...(initial.collection==='resources'?{fileSize:`${(asset.size/1024).toFixed(1)} KB`,fileFormat:asset.mime==='application/pdf'?'PDF':asset.mime.split('/')[1].toUpperCase(),versionDate:new Date().toISOString().slice(0,10)}:{})}}));
  const resourceField=initial.collection==='committees'?'backgroundGuideDocId':initial.collection==='moot-categories'?'propositionDocId':null;
  return <div className="admin-card">{!readOnly&&mediaField&&<><label>Choose library media<select value="" onChange={e=>{const asset=media.find(a=>a.url===e.target.value);if(asset)chooseMedia(asset);}}><option value="">Select media</option>{media.filter(a=>initial.collection==='resources'||a.mime.startsWith('image/')).map(a=><option key={a.url} value={a.url}>{a.alt}</option>)}</select></label>{upload&&<MediaUpload onUploaded={assets=>{const asset=assets.find(a=>initial.collection==='resources'||a.mime.startsWith('image/'));if(asset)chooseMedia(asset);}}/>}</>}{!readOnly&&resourceField&&<label>Choose published resource<select value={String(entry.data[resourceField]||'')} onChange={e=>setEntry(old=>({...old,data:{...old.data,[resourceField]:e.target.value}}))}><option value="">Choose resource</option>{resources.map(r=><option key={r.id} value={r.id}>{r.title}</option>)}</select></label>}<form onSubmit={e => { e.preventDefault(); execute(() => settings ? saveSettings(entry.data,entry.version) : saveContent(entry)); }}><fieldset disabled={readOnly || pending}><SchemaForm schema={schema} value={entry.data} onChange={v => { const data = v as Record<string,unknown>; setEntry({ ...entry,data,id: settings ? 'site' : String(data.id || '') }); }} />{!settings && <><label>Publication state<select value={entry.status} onChange={e => setEntry({ ...entry,status:e.target.value as ContentEntry['status'] })}>{['draft','published','archived'].map(v => <option key={v}>{v}</option>)}</select></label><label>Sort order<input type="number" value={entry.sort_order} onChange={e => setEntry({ ...entry,sort_order:Number(e.target.value) })} /></label><label>Publish at (UTC)<input type="datetime-local" value={entry.publish_at?.slice(0,16) || ''} onChange={e => setEntry({ ...entry,publish_at:e.target.value ? `${e.target.value}:00Z` : null })} /></label><label>Expire at (UTC)<input type="datetime-local" value={entry.expire_at?.slice(0,16) || ''} onChange={e => setEntry({ ...entry,expire_at:e.target.value ? `${e.target.value}:00Z` : null })} /></label></>}<button disabled={pending || readOnly}>Save changes</button></fieldset></form>{message && <p role="status">{message}</p>}<h2>Revisions</h2>{revisions.map(revision => <p key={revision.id}>{revision.created_at} <button disabled={pending || readOnly} onClick={() => execute(() => restoreRevision(revision.id,entry.version))}>Restore revision {revision.id}</button></p>)}</div>;
}
