'use server';
import { randomUUID } from 'node:crypto';
import { z } from 'zod';
import { revalidatePath } from 'next/cache';
import { unstable_rethrow } from 'next/navigation';
import { requirePermission } from '@backend/server/admin/auth';
import { someRow } from '@backend/server/admin/read-all';
import { database } from '@backend/server/supabase';
const types={'image/jpeg':'jpg','image/png':'png','image/webp':'webp','application/pdf':'pdf'} as const;
export type UploadedMedia={url:string;alt:string;size:number;mime:string;path:string};
/**
 * Every action returns `{ error }` instead of throwing. In a production build
 * Next replaces the message of an error thrown from a server action with a
 * generic one, so "File is too large" reached the editor as "An error
 * occurred in the Server Components render".
 */
export type MediaResult<T>=T|{error:string};
function failure(error:unknown,fallback:string){unstable_rethrow(error);return {error:error instanceof MediaError?error.message:fallback};}
class MediaError extends Error{}
// Storage paths are generated by this module, but the server actions also
// accept retry/delete requests from an older admin tab. Keep the contract
// strict without rejecting those already-created flat object names.
const mediaPath=z.string().regex(/^[a-zA-Z0-9][a-zA-Z0-9._-]{0,255}$/,'Invalid media path.');
const MEDIA_LIMITS={image:5*1024*1024,pdf:25*1024*1024} as const;
const uploadInput=z.object({mime:z.enum(['image/jpeg','image/png','image/webp','application/pdf']),size:z.number().int().positive(),alt:z.string().trim().min(1,'Add a short description so this file is easy to find and accessible.').max(500)});
function safePathOf(path:unknown){const parsed=mediaPath.safeParse(path);if(!parsed.success)throw new MediaError('Invalid media path.');return parsed.data;}
async function writer(){try{return await requirePermission('media',true);}catch(error){unstable_rethrow(error);throw new MediaError('You do not have permission to manage media. Sign in again or ask an owner for access.');}}
export async function startUpload(input:unknown):Promise<MediaResult<{path:string;token:string}>>{
  try{
    const user=await writer();
    const parsed=uploadInput.safeParse(input);
    if(!parsed.success)throw new MediaError('Choose a JPEG, PNG, WebP or PDF file and add a description.');
    if(parsed.data.size>(parsed.data.mime==='application/pdf'?MEDIA_LIMITS.pdf:MEDIA_LIMITS.image))throw new MediaError('File is too large. Images: 5 MB; PDFs: 25 MB.');
    // Random object name only: public URLs must not reveal which admin uploaded the file.
    const path=`${randomUUID()}.${types[parsed.data.mime]}`;
    const db=database();const {data,error}=await db.storage.from('media').createSignedUploadUrl(path,{upsert:false});
    if(error||!data?.token)throw new MediaError('The media storage is unavailable. Check the media bucket and try again.');
    const {error:insertError}=await db.from('media_assets').insert({path,mime:parsed.data.mime,size:parsed.data.size,alt:parsed.data.alt,uploaded_by:user.user_id,state:'pending'});
    if(insertError){await db.storage.from('media').remove([path]);throw new MediaError('The upload was not recorded. No file was kept. Try again.');}
    return {path,token:data.token};
  }catch(error){return failure(error,'The upload could not start. Check the CMS connection and try again.');}
}
export async function finishUpload(path:string):Promise<MediaResult<UploadedMedia>>{
  try{
    const safePath=safePathOf(path);
    const user=await writer();const db=database();
    const {data:asset,error}=await db.from('media_assets').select('*').eq('path',safePath).eq('uploaded_by',user.user_id).single();
    if(error||!asset)throw new MediaError('Upload is not owned by this account.');
    if(asset.state==='available')return {url:db.storage.from('media').getPublicUrl(safePath).data.publicUrl,size:Number(asset.size),mime:String(asset.mime),alt:String(asset.alt||''),path:safePath};
    if(asset.state!=='pending')throw new MediaError('This upload cannot be verified in its current state.');
    const {data:info,error:infoError}=await db.storage.from('media').info(safePath);
    if(infoError||Number(info?.size)!==Number(asset.size)||info?.contentType!==asset.mime){
      // Do not leave a metadata row pointing at a missing or mismatched file.
      const removed=await db.storage.from('media').remove([safePath]);
      if(removed.error)throw new MediaError('File verification failed and cleanup could not finish. Retry cleanup.');
      const deleted=await db.from('media_assets').delete().eq('path',safePath).eq('uploaded_by',user.user_id).eq('state','pending');
      if(deleted.error)throw new MediaError('Invalid file removed, but metadata cleanup failed. Retry cleanup.');
      throw new MediaError('The uploaded file did not match its declared size or type, so it was discarded. Choose the file again.');
    }
    const verified=await db.from('media_assets').update({state:'available'}).eq('path',safePath).eq('uploaded_by',user.user_id);
    if(verified.error)throw new MediaError('File uploaded but verification could not be recorded. Retry verification.');
    revalidatePath('/admin/media');
    return {url:db.storage.from('media').getPublicUrl(safePath).data.publicUrl,size:Number(asset.size),mime:String(asset.mime),alt:String(asset.alt||''),path:safePath};
  }catch(error){return failure(error,'The upload could not be verified. Try again.');}
}
/** Clears a row whose upload never completed (the browser upload failed or was abandoned). */
export async function abandonUpload(path:string):Promise<MediaResult<{removed:true}>>{
  try{
    const safePath=safePathOf(path);
    const user=await writer();const db=database();
    const {data:asset,error}=await db.from('media_assets').select('path,state').eq('path',safePath).eq('uploaded_by',user.user_id).eq('state','pending').maybeSingle();
    if(error||!asset)throw new MediaError('Pending upload not found for this account.');
    const removed=await db.storage.from('media').remove([asset.path]);if(removed.error)throw new MediaError('Upload cleanup failed.');
    const deleted=await db.from('media_assets').delete().eq('path',asset.path).eq('uploaded_by',user.user_id).eq('state','pending');if(deleted.error)throw new MediaError('Upload metadata cleanup failed.');
    return {removed:true};
  }catch(error){return failure(error,'The incomplete upload could not be removed. Try again.');}
}
/** Deletes a file only when no content entry, setting, revision, publication or archive still links to it. */
export async function deleteMedia(id:string):Promise<MediaResult<{result:string}>>{
  try{
    await writer();
    const assetId=z.uuid().safeParse(id);if(!assetId.success)return {error:'Media not found.'};
    const db=database();
    const {data:asset,error}=await db.from('media_assets').select('path').eq('id',assetId.data).single();
    if(error||!asset)return {error:'Media not found.'};
    // The object name is a random UUID, so it identifies the file in any stored
    // link, whichever host or URL form the link was saved with.
    const needle=String(asset.path);
    const uses=(row:Record<string,unknown>)=>JSON.stringify(row).includes(needle);
    let referenced=false;
    try{
      for(const [table,select,order] of [['content_entries','collection,id,data','id'],['site_settings','data','id'],['content_publications','data','release_id'],['event_archives','snapshot','id'],['content_revisions','snapshot','id']] as const){
        if(await someRow(table,select,order,uses)){referenced=true;break;}
      }
    }catch{return {error:'Unable to verify file references. No file was deleted.'};}
    if(referenced)return {error:'This file is retained by content, a revision, a publication, or an archive. Replace it without deleting the original.'};
    const removed=await db.storage.from('media').remove([asset.path]);if(removed.error)return {error:'Unable to delete the file.'};
    const deleted=await db.from('media_assets').delete().eq('id',assetId.data);if(deleted.error)return {error:'File removed, but metadata cleanup failed. Retry deletion.'};revalidatePath('/admin/media');return {result:'Deleted.'};
  }catch(error){return failure(error,'The file could not be deleted. Try again.');}
}
