'use client';
import { useRef,useState,useEffect } from 'react';
import { BrowserQRCodeReader,type IScannerControls } from '@zxing/browser';
import { lookupAttendees,runOperation } from './ops-actions';
type Roster={reference_id:string;applicant_name:string;status:string;payment_status:string;participants:{id:string;name:string;role:string;checked_in_at:string|null}[]};
export function Scanner({allowOverride=false}:{allowOverride?:boolean}){const [override,setOverride]=useState(false);const [reason,setReason]=useState('');const video=useRef<HTMLVideoElement>(null);const controls=useRef<IScannerControls|null>(null);const [value,setValue]=useState('');const [roster,setRoster]=useState<Roster|null>(null);const [message,setMessage]=useState('');const [pending,setPending]=useState(false);
  useEffect(()=>()=>controls.current?.stop(),[]);
  async function lookup(code:string){setPending(true);try{const r=await lookupAttendees(code);setMessage(r.error||'');setRoster(r.result as Roster || null);}catch{setMessage('Lookup failed. Check your connection.');}finally{setPending(false);}}
  async function camera(){try{controls.current?.stop();controls.current=await new BrowserQRCodeReader().decodeFromVideoDevice(undefined,video.current!,result=>{if(result){const code=result.getText();controls.current?.stop();setValue(code);void lookup(code);}});}catch{setMessage('Camera unavailable. Use manual reference lookup.');}}
  return <div className="admin-card"><h2>Ticket check-in</h2><button className="print:hidden" onClick={()=>window.print()}>Print current roster / badge details</button><button onClick={camera}>Start camera</button><button onClick={()=>controls.current?.stop()}>Stop camera</button><video ref={video} className="max-w-sm w-full" muted playsInline/><form onSubmit={e=>{e.preventDefault();void lookup(value);}}><label>Ticket token or registration reference<input value={value} onChange={e=>setValue(e.target.value)} required/></label><button disabled={pending}>Look up roster</button></form>{message&&<p role="status">{message}</p>}{allowOverride&&<fieldset><legend>Registrar override</legend><label><input type="checkbox" checked={override} onChange={e=>setOverride(e.target.checked)}/>Override acceptance/payment eligibility</label>{override&&<label>Recorded reason<input value={reason} onChange={e=>setReason(e.target.value)} minLength={5}/></label>}</fieldset>}{roster&&<div><h2>{roster.applicant_name}</h2><p>{roster.reference_id} · {roster.status} · {roster.payment_status}</p>{roster.participants.map(p=><div key={p.id} className="flex items-center justify-between gap-4 border-b py-3"><span>{p.name} · {p.role}</span><button disabled={pending} onClick={async()=>{setPending(true);try{const r=await runOperation('checkin',{participant_id:p.id,checked:!p.checked_in_at,override,reason});if(r.error)setMessage(r.error);else{await lookup(value);setMessage('Attendance saved.');}}catch{setMessage('Attendance could not be saved. Try again.');}finally{setPending(false);}}}>{p.checked_in_at?'Undo check-in':'Check in'}</button></div>)}</div>}</div>;
}
