import { beforeEach,afterEach,it,expect,vi } from 'vitest';
vi.mock('next/cache',()=>({unstable_cache:(fn:unknown)=>fn}));
vi.mock('@/lib/content',()=>({getSiteConfig:async()=>({eventDates:{start:'2028-01-01',end:'2028-01-04'},eventNames:{combined:'Test'},contactEmails:{general:'a@example.test'},hostInstitution:'Test University',venue:'Test'})}));
const rpc=vi.fn(),update=vi.fn();
vi.mock('@/lib/server/supabase',()=>({database:()=>({rpc,from:()=>({update:()=>({eq:()=>({eq:update})})})})}));
import { createRegistration,enforceRateLimit,dispatchEmailOutbox } from '../../src/lib/server/submissions';
beforeEach(()=>{vi.stubEnv('NODE_ENV','test');vi.stubEnv('SUBMISSIONS_BACKEND','memory');vi.stubEnv('UPSTASH_REDIS_REST_URL','');vi.stubEnv('UPSTASH_REDIS_REST_TOKEN','');rpc.mockReset();update.mockReset();});
afterEach(()=>{vi.unstubAllEnvs();vi.unstubAllGlobals();});
it.each([['concurrent_idempotent_requests',1,0],['invalid_idempotent_request',0,1]])('handles Resend conflict %s',async(name,retried,failed)=>{
  vi.stubEnv('SUBMISSIONS_BACKEND','supabase');vi.stubEnv('RESEND_API_KEY','test');vi.stubEnv('EMAIL_FROM','test@example.test');
  rpc.mockResolvedValue({data:[{id:'conflict-id',from_address:'test@example.test',to_addresses:['a@example.test'],subject:'Test',html:'original',attempts:1,retry_until:new Date(Date.now()+3600000).toISOString()}],error:null});update.mockResolvedValue({error:null});
  vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(JSON.stringify({name}),{status:409})));
  const result=await dispatchEmailOutbox();expect(result.retried).toBe(retried);expect(result.failed).toBe(failed);
});
it('uses EVAL with a key count and expiry in Upstash',async()=>{vi.stubEnv('UPSTASH_REDIS_REST_URL','https://example.test');vi.stubEnv('UPSTASH_REDIS_REST_TOKEN','test');const fetch=vi.fn().mockResolvedValue(new Response(JSON.stringify({result:1})));vi.stubGlobal('fetch',fetch);expect((await enforceRateLimit('test','127.0.0.1')).allowed).toBe(true);const payload=JSON.parse(fetch.mock.calls[0][1].body);expect(payload[0]).toBe('EVAL');expect(payload[2]).toBe(1);expect(payload[4]).toBeGreaterThan(0);expect(payload[3]).not.toContain('127.0.0.1');});
it('reuses the receipt and token for an identical submission key',async()=>{const record={submissionKey:crypto.randomUUID(),amountDue:4500,track:'gimun' as const,applicantType:'individual' as const,formData:{fullName:'Test',email:'a@example.test'} as never,applicantName:'Test',institution:'Test',email:'a@example.test',participantCount:1,submittedAt:new Date().toISOString()};const first=await createRegistration(record),second=await createRegistration(record);expect(first).toEqual(second);expect(first.referenceId).toMatch(/^REG-GIMUN-2028-/);expect(first.checkinToken).toMatch(/^[0-9a-f-]{36}$/);await expect(createRegistration({...record,formData:{fullName:'Changed'} as never})).rejects.toThrow('different details');});
it('retries uncertain delivery with the unchanged provider key',async()=>{vi.stubEnv('SUBMISSIONS_BACKEND','supabase');vi.stubEnv('RESEND_API_KEY','test');vi.stubEnv('EMAIL_FROM','test@example.test');rpc.mockResolvedValue({data:[{id:'message-id',from_address:'test@example.test',to_addresses:['a@example.test'],subject:'Test',html:'original',attempts:1,retry_until:new Date(Date.now()+3600000).toISOString()}],error:null});const updates:unknown[]=[];update.mockImplementation(()=>{updates.push('updated');return {error:null};});const fetch=vi.fn().mockRejectedValue(new Error('timeout'));vi.stubGlobal('fetch',fetch);const result=await dispatchEmailOutbox();expect(result.retried).toBe(1);expect(result.needsReview).toBe(0);expect(fetch.mock.calls[0][1].headers['Idempotency-Key']).toBe('gimun-outbox/message-id');expect(updates).toHaveLength(1);});
it('leaves the lease untouched if recording a successful send fails',async()=>{vi.stubEnv('SUBMISSIONS_BACKEND','supabase');vi.stubEnv('RESEND_API_KEY','test');vi.stubEnv('EMAIL_FROM','test@example.test');rpc.mockResolvedValue({data:[{id:'sent-id',from_address:'test@example.test',to_addresses:['a@example.test'],subject:'Test',html:'original',attempts:1,retry_until:new Date(Date.now()+3600000).toISOString()}],error:null});update.mockResolvedValue({error:{message:'database unavailable'}});vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(JSON.stringify({id:'provider-id'}))));await dispatchEmailOutbox();expect(update).toHaveBeenCalledTimes(1);});
